name: 功能请求（使用中文）
description: 提出新功能建议或改进意见
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
        - label: 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速了解建议内容
          required: true
        - label: 我基本确定这是一个新功能/改进建议，而不是遇到了 Bug
          required: true
        - label: 我使用的是最新版本，且已查看最新版本发布说明和未发布的更新内容，确认我的建议未被提及
          required: true
        - label: 我已检查了置顶议题（Pinned Issue）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及
          required: true
  - type: textarea
    id: problem
    attributes:
      label: 遇到的问题是什么？
      description: 请描述你希望解决的问题或痛点
      placeholder: |
        例如：每次保存页面时都需要手动选择 Notion 数据库，很不方便...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: 你期望的解决方案是什么？
      description: 请描述你希望的功能或改进
      placeholder: |
        例如：希望能够设置默认数据库，每次保存时自动使用默认数据库，不需要手动选择...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 有考虑过其他替代方案吗？
      description: 如果有其他可能的实现方式，请描述
      placeholder: |
        例如：也可以记住上次选择的数据库，作为下次的默认选项...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 其他补充信息
      description: |
        关于该功能请求的任何其他背景、截图或参考资料
        例如可以提供其他类似工具的实现作为参考
    validations:
      required: false
