name: 其他问题（使用中文）
description: 其他类型的问题、疑问或讨论
labels: ["question"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
        - label: 我填写了简短且清晰明确的标题
          required: true
        - label: 我已阅读了文档和 README
          required: true
        - label: 我已检查了置顶议题（Pinned Issue）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及
          required: true
  - type: textarea
    id: content
    attributes:
      label: 问题描述
      description: 请描述你的问题、疑问或想讨论的内容
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 其他补充信息
      description: 任何其他有助于理解你问题的信息
    validations:
      required: false
